[package]
name = "aoc-2019"
version = "0.1.0"
authors = ["Geobert Quach <geobert.quach@hutchison-t.com>"]
edition = "2018"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
